### ISSUE TITLE
mysql.jiankang.10086.cn

### ISSUE THREAD

**Issue by zhengty** [favccxx/FavOAuth2#3]
这是什么地址啊~！有数据库脚本吗？

**Comment by favccxx** [comment]
CREATE TABLE "OMYGOOD"."FAV_AUTH_USER" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"BIRTHDAY" TIMESTAMP (6), 
	"NICK_NAME" VARCHAR2(255 CHAR), 
	"USER_MAIL" VARCHAR2(255 CHAR), 
	"USER_NAME" VARCHAR2(255 CHAR), 
	"USER_PWD" VARCHAR2(255 CHAR), 
	"USER_STATUS" VARCHAR2(255 CHAR), 
	"USER_TEL" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING NOCOMPRESS LOGGING
  TABLESPACE "REPORTSERVER"  ENABLE, 
	 CONSTRAINT "UK_LI77MX49X58W5WSUDJBBA2P53" UNIQUE ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "REPORTSERVER"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  TABLESPACE "REPORTSERVER" ;
 
  CREATE UNIQUE INDEX "OMYGOOD"."SYS_C0016249" ON "OMYGOOD"."FAV_AUTH_USER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING NOCOMPRESS LOGGING
  TABLESPACE "REPORTSERVER" ;
 
  CREATE UNIQUE INDEX "OMYGOOD"."UK_LI77MX49X58W5WSUDJBBA2P53" ON "OMYGOOD"."FAV_AUTH_USER" ("USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "REPORTSERVER" ;
 
  ALTER TABLE "OMYGOOD"."FAV_AUTH_USER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "OMYGOOD"."FAV_AUTH_USER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING NOCOMPRESS LOGGING
  TABLESPACE "REPORTSERVER"  ENABLE;
 
  ALTER TABLE "OMYGOOD"."FAV_AUTH_USER" ADD CONSTRAINT "UK_LI77MX49X58W5WSUDJBBA2P53" UNIQUE ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "REPORTSERVER"  ENABLE;

**Comment by favccxx** [comment]
新版使用了Hibernate，无需单独使用脚本初始化数据库。
